data_path: /home/x/catkin_ws/src/lidar_localization   # 数据存放路径
target_file: ../data/cloud-87.pcd
source_file: ../data/cloud-89.pcd
ds_size: 0.005

# 匹配
# TODO: implement your custom registration method and add it here
registration_method: ICP_GN   # 选择点云匹配方法，目前支持：ICP,ICP_GN, ICP_SVD,ICP_CERES,ICP_G2O, NDT, SICP,NDT_CPU

# 各配置选项对应参数
## 匹配相关参数
ICP:
    max_corr_dist : 1.0
    trans_eps : 0.01
    euc_fitness_eps : 0.36
    max_iter : 30
ICP_GN:
    max_corr_dist : 1.0
    trans_eps : 0.01
    euc_fitness_eps : 0.36
    max_iter : 10
ICP_CERES:
    max_corr_dist : 1.0
    trans_eps : 0.01
    euc_fitness_eps : 0.36
    max_iter : 15
ICP_G2O:
    max_corr_dist : 1.0
    trans_eps : 0.01
    euc_fitness_eps : 0.36
    max_iter : 15
ICP_SVD:
    max_corr_dist : 1.0
    trans_eps : 0.01
    euc_fitness_eps : 0.36
    max_iter : 10
NDT:
    res : 1.0                 # volex  resolution
    step_size : 0.1    # 梯度下降的步长，越大下降越快，但是容易over shoot陷入局部最优
    trans_eps : 0.01    # 最大容差，一旦两次转换矩阵小于 trans_eps  退出迭代
    max_iter : 30         #   最大迭代次数
NDT_CPU:
    res : 0.8                 # volex  resolution
    step_size : 0.1    # 梯度下降的步长，越大下降越快，但是容易over shoot陷入局部最优
    trans_eps : 0.01    # 最大容差，一旦两次转换矩阵小于 trans_eps  退出迭代
    max_iter : 30         #   最大迭代次数
SICP:
    p : 1.0
    mu : 10.0
    alpha : 1.2
    max_mu : 1e5
    max_icp : 100
    max_outer : 100
    max_inner : 1
    stop : 1e-5